### ISSUE TITLE
Run webserver automatically from runchrono.py

### ISSUE THREAD

**Issue by jomarin38** [jomarin38/F3FChrono#45]
The configuration to start or not the webserver should be done in config.json file.
Maybe there is a better way to do that from python than using os.system(python3 manage.py runserver ... )

**Comment by jomarin38** [comment]
Closed by #46

**Comment by sdaviet** [comment]
the web server doesn't work correctly. 
console log : 
System check identified no issues (0 silenced).
March 02, 2020 - 15:42:44
Django version 3.0.2, using settings 'F3FChrono.web.webinterface.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Not Found: /
[02/Mar/2020 15:42:49] "GET / HTTP/1.1" 404 2050
Not Found: /
[02/Mar/2020 15:43:12] "GET / HTTP/1.1" 404 2052

web page log :

Page not found (404)
Request Method: 	GET
Request URL: 	http://10.0.2.15:8000/

Using the URLconf defined in F3FChrono.web.webinterface.urls, Django tried these URL patterns, in this order:

    f3franking/
    admin/

The empty path didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by jomarin38** [comment]
the url to use is :
http://10.0.2.15:8000/f3franking
Did you put the 'f3franking' ?

**Comment by sdaviet** [comment]
ok, it work with this url.
but the css file doesn't work ;) in the ranking view
